#cloud-config
package_update: true
package_upgrade: true
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release

runcmd:
  # Install Docker (Ubuntu repo is fine for this lab)
  - apt-get update -y
  - apt-get install -y docker.io
  - systemctl enable docker
  - systemctl start docker
  - usermod -aG docker ubuntu || true  # change user if different
  - newgrp docker <<EOF echo "Docker ready"
   EOF