trigger:
- azure-devops-demo

pool:
  name: linux-hosted-agent

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Hello, world!
    uname -a
    whoami
    df -h

  displayName: 'Run a multi-line script'
