---
#Play 1: Prepare web servers
- name: Prepare web servers
  hosts: web
  become: yes
  tasks:
    - name: Ensure Nginx is installed
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Ensure Nginx is running and enabled
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes


#Play 2: Deploy web content
- name: Deploy index.html to web servers
  hosts: web
  become: yes
  tasks:
    - name: Copy index.html to the web root
      ansible.builtin.copy:
        src: files/index.html
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'


#Play 3: Verify deployment
- name: Verify web page content from controller
  hosts: localhost
  tasks:
    - name: Check each web server is serving index.html
      ansible.builtin.uri:
        url: "http://{{ item }}"
        return_content: yes
      loop: "{{ groups['web'] }}"
      register: web_check

    - name: Print response summary
      ansible.builtin.debug:
        msg: "Host {{ item.item }} responded with: {{ item.content | truncate(60, True) }}"
      loop: "{{ web_check.results }}"

